### PR TITLE
[fix] `document.documentElement` undefined

### LINKED ISSUE #116: User script crashes during initialization when calling `document.documentElement.append()`
Please do something (Happens on google chrome)

### PR DESCRIPTION
**Pull request by drunkwinter**
Fixes #116

### CODE REVIEW

**Comment by zerodytrash** [comment]
That was quick! 
But what about this approach?
Less code and also seems to work.

**Comment by drunkwinter** [comment]
That value may not exist on mobile, on top of that we are moving the same element over and over again on each toast call

**Comment by drunkwinter** [comment]
Woops it does i somehow thought it was a custom element value..

**Comment by drunkwinter** [comment]
Yeah this looks good for merge... kinda misunderstood the whole idea :P

**Review by zerodytrash — APPROVED** [review]
Okay, quick & simple fix

**Pull request merged**
