### PR TITLE
Filter out video ads missed by uBlock Origin when Age Restriction Bypass script is enabled

### LINKED ISSUE #6: Breaks uBlock Origin?
Not sure what causes this but I always get this before the video starts when the script is enabled, even when the video is not age restricted:
image

Using Firefox 87.0 with Tampermonkey 4.12.6132

### PR DESCRIPTION
**Pull request by JustOff**
This addresses the race condition between Age Restriction Bypass script and uBlock Origin.

Resolves #6.

### CODE REVIEW

**Comment by zerodytrash** [comment]
hi,

Thanks for your fix. But i would prefer not to use such functions, because this is not an adblock script. Nevertheless, compatibility with adblock extensions should be possible.

I think I found a solution for the uBlock problem in firefox:

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/1874086c0fed5d7c7bbfa1ccd6a56be3229bdae1#diff-2a1805cada304e81c09a34b8192d79fcd73c736b0bb85d90fc1ef3b813e0bfa1

If this does not work, we can look again whether an adblock function should be implemented.

**Comment by JustOff** [comment]
I'm afraid your solution [does not clear the issue](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/6#issuecomment-854472063).

**Comment by JustOff** [comment]
Just for the record, the corresponding issue remains unresolved.

**Comment by zerodytrash** [comment]
Most people don't have the problem (see https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/6). I also use the script in firefox in combination with ublock without ads. I still think that the script should only do what it is supposed to do. It's not an adblocker. But it should be compatible with adblocker. Do you maybe have another solution for this problem?

**Pull request closed without merging**
