### PR TITLE
Fix video description & suggested videos

### LINKED ISSUE #76: Video description and the videos on right side not appearing
I tried watching HowToBasic - How To Make a Rainbow Cake
but the description didnt appear; neither did the sidebar of videos
Snímek obrazovky 2021-09-10 104651

### PR DESCRIPTION
**Pull request by DrunkWinter**
Fixes #76

### CODE REVIEW

**Comment by DrunkWinter** [comment]
Why did we need the `isUserLoggedIn` and `isWatchNextSidebarEmpty` check in the first place?

It seems we are not using unlock method 2, even for mobile. Can it be removed?

**Comment by zerodytrash** [comment]
Have tested this last days. Unlock 2 is used by m.youtube.com. To reproduce this you have to search for an age-restricted video on the start page. When selecting the video the following request is made: `https://m.youtube.com/watch?v={videoId}&pbj=1`. The response corresponds to the layout of unlock 2. But YouTube will also replace this request with the innertube API in the near future. Until then we have to keep it...

The `isWatchNextSidebarEmpty` check prevents changes to the sidebar if the sidebar is not empty. This is necessary because the API request to unlock the sidebar is executed without authentication. Your change would remove user-related suggestions on any video. Therefore, we need to apply the sidebar unlock only when it is necessary.

To avoid false positives with the `isWatchNextSidebarEmpty` check as soon as YouTube changes something in the response layout, I had implemented additionally the `isLoggedIn` check. Because if the user is logged in, an unlock of the sidebar is generally not necessary.

**Comment by DrunkWinter** [comment]
> Have tested this last days. Unlock 2 is used by m.youtube.com. To reproduce this you have to search for an age-restricted video on the start page. When selecting the video the following request is made: `https://m.youtube.com/watch?v={videoId}&pbj=1`. The response corresponds to the layout of unlock 2. But YouTube will also replace this request with the innertube API in the near future. Until then we have to keep it...
> 
> The `isWatchNextSidebarEmpty` check prevents changes to the sidebar if the sidebar is not empty. This is necessary because the API request to unlock the sidebar is executed without authentication. Your change would remove user-related suggestions on any video. Therefore, we need to apply the sidebar unlock only when it is necessary.
> 
> To avoid false positives with the `isWatchNextSidebarEmpty` check as soon as YouTube changes something in the response layout, I had implemented additionally the `isLoggedIn` check. Because if the user is logged in, an unlock of the sidebar is generally not necessary.

Makes sense, except the sidebar is always empty when the video is age-restricted, therefore the check here would be unnecessary.

As for the `isLoggedIn` check, I think it makes sense to remove it, since we want to display something to the user, even if it's not their personalized feed rather than nothing, in the future we could also provide the login information which would fit perfectly. In addition we need this check to pass since the video description is also handled in the same function. 

What do you think?

**Comment by zerodytrash** [comment]
> Makes sense, except the sidebar is always empty when the video is age-restricted, therefore the check here would be unnecessary.

We still need to test if the sidebar is empty. Otherwise a replacement of the sidebar und comments would take place every time **even for non-age restricted videos**.

> As for the isLoggedIn check, I think it makes sense to remove it, since we want to display something to the user, even if it's not their personalized feed rather than nothing

It was checked for `!isLoggedIn()`. This triggered a sidebar unlock only when the user **is not logged in and the sidebar is empty**. So **nothing** would never be displayed at all.

Possible side effects when we remove the `!isLoggedIn()` check and keep the `isWatchNextSidebarEmpty()` check:
- If the `isWatchNextSidebarEmpty` function always returns true due to a response layout change by YouTube, the unlock would always be executed and all personalized suggestions would be removed (even for non-age-restricted videos). 

Side effects when we remove the `isWatchNextSidebarEmpty()` check and keep the `!isLoggedIn()`. check:
- If the user is not logged in, the sidebar of all videos would be replaced by the unlock (even for non-age-restricted videos). The video suggestions would be the same, but the unlock attempt is pointless.

I prefer to keep both checks to have a fallback if the `isWatchNextSidebarEmpty()` function breaks.

**Comment by DrunkWinter** [comment]
> 
> We still need to test if the sidebar is empty. Otherwise a replacement of the sidebar und comments would take place every time **even for non-age restricted videos**.
> 
I completely forgot that this function ran even when the video doesn't need an unlock!
> 
> It was checked for `!isLoggedIn()`. This triggered a sidebar unlock only when the user **is not logged in and the sidebar is empty**. So **nothing** would never be displayed at all.
>
For me, every locked video has no video description and no suggested content either, because I'm logged in. 
This check always fails when the user is logged in.
> Possible side effects when we remove the `!isLoggedIn()` check and keep the `isWatchNextSidebarEmpty()` check:
> 
> * If the `isWatchNextSidebarEmpty` function always returns true due to a response layout change by YouTube, the unlock would always be executed and all personalized suggestions would be removed (even for non-age-restricted videos).
> 
> Side effects when we remove the `isWatchNextSidebarEmpty()` check and keep the `!isLoggedIn()`. check:
> 
> * If the user is not logged in, the sidebar of all videos would be replaced by the unlock (even for non-age-restricted videos). The video suggestions would be the same, but the unlock attempt is pointless.
> 
> I prefer to keep both checks to have a fallback if the `isWatchNextSidebarEmpty()` function breaks.

My proposal (pseudo code):

This should solve the issues described above, without the need of `!isLoggedIn` or `isWatchNextSidebarEmpty`.

```javascript
let wasVideoOriginallyLocked = false;

if (isAgeRestricted()) wasVideoOriginallyLocked = true;

if (isWatchNextObject() && wasVideoOriginallyLocked) {
    // Video was originally locked, which means the sidebar is confirmed empty. 
    // Therefore we can replace the sidebar with confidence.
    
    ytData = unlocker.unlockNextResponse(ytData);
}
```

**Comment by DrunkWinter** [comment]
Also made `if` -> `else if`, to prevent useless checks when the unlock method is already determined.

**Comment by DrunkWinter** [comment]
Just need to reset the bool.. will do that tomorrow

**Review by zerodytrash — COMMENTED** [review]
> For me, every locked video has no video description and no suggested content either, because I'm logged in.

For me the video description and video suggestions are available when i am logged in. Even if the video is age restricted. This change currently overrides the personalized video suggestions for me.

Furthermore the code only works if the player request is made before the next request. On the mobile Website this causes a race condition.

I would suggest to use `isWatchNextObject` and `isWatchNextSidebarEmpty` without `isUserLoggedIn`. This seems to be the most stable way at the moment.

> Possible side effects when we remove the !isLoggedIn() check and keep the isWatchNextSidebarEmpty() check:
If the isWatchNextSidebarEmpty function always returns true due to a response layout change by YouTube, the unlock would always be executed and all personalized suggestions would be removed (even for non-age-restricted videos).

That was not correct. The unlocked response is also checked by the `isWatchNextSidebarEmpty` function. If it still returns `true`, the sidebar is left unchanged. 
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/22d140c8026c8b4f21f47e68ab3b32706cb1cbc3/src/components/unlocker.js#L83
Therefore the risk is manageable :)

**Comment by DrunkWinter** [comment]
> > For me, every locked video has no video description and no suggested content either, because I'm logged in.
> 
> For me the video description and video suggestions are available when i am logged in. Even if the video is age restricted. This change currently overrides the personalized video suggestions for me.
> 
> Furthermore the code only works if the player request is made before the next request. On the mobile Website this causes a race condition.
> 
> I would suggest to use `isWatchNextObject` and `isWatchNextSidebarEmpty` without `isUserLoggedIn`. This seems to be the most stable way at the moment.
> 
> > Possible side effects when we remove the !isLoggedIn() check and keep the isWatchNextSidebarEmpty() check:
> > If the isWatchNextSidebarEmpty function always returns true due to a response layout change by YouTube, the unlock would always be executed and all personalized suggestions would be removed (even for non-age-restricted videos).
> 
> That was not correct. The unlocked response is also checked by the `isWatchNextSidebarEmpty` function. If it still returns `true`, the sidebar is left unchanged.
> https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/22d140c8026c8b4f21f47e68ab3b32706cb1cbc3/src/components/unlocker.js#L83
> 
> 
> Therefore the risk is manageable :)

That's really interesting #76 is exactly the problem I was having also.. What would the reason be that it works for on your end you think? Country maybe? Or maybe the `isUserLoggedIn` check returns false for you for some other reason?

Also the weird thing is I tested on the mobile version of the site and it worked without issues, because in both versions the player request is always first.

Anyway I'm going to change it to back to `isWatchNextObject` without the login check then.

**Comment by zerodytrash** [comment]
>  What would the reason be that it works for on your end you think? Country maybe?
Yes, maybe the location or an A/B test. idk

> Anyway I'm going to change it to back to isWatchNextObject without the login check then.
ok, that should fix the problem for everyone.

**Comment by DrunkWinter** [comment]
Ready for merge

**Pull request merged**
