### PR TITLE
Catch age-gated videos with music embed restrictions for /player bypass

### PR DESCRIPTION
**Pull request by MinePlayersPE**
e.g. https://www.youtube.com/watch?v=HsUATh_Nc2U where the copyrighted music causes the embed to only work when on a public domain
Based off https://stackoverflow.com/a/59640711

### CODE REVIEW

**Comment by MinePlayersPE** [comment]
Signature timestamp was also required (otherwise the videos would 403), so I added it (you might want to dynamically get it from the webpage tho)

**Comment by zerodytrash** [comment]
Sweet! In my test, only the `embedUrl` was required. it also worked without `signatureTimestamp`.

**Comment by JustOff** [comment]
In my environment, providing proper signatureTimestamp is necessary.  This requires changing just one line: 

```diff
-                    "signatureTimestamp": 18830
+                    "signatureTimestamp": ytcfg.get("STS")
```

**Comment by zerodytrash** [comment]
i didn't notice that the ytcfg object has a nice getter :)

**Pull request merged**
