### PR TITLE
[fix] embed strategy

### PR DESCRIPTION
**Pull request by drunkwinter**
Also required some refactoring to be more flexible.

### CODE REVIEW

**Comment by drunkwinter** [comment]
@zerodytrash Could you test if the second strategy (creator + auth) behaves correctly?

**Comment by zerodytrash** [comment]
> Could you test if the second strategy (creator + auth) behaves correctly?

@drunkwinter yes, works!

**Comment by zerodytrash** [comment]
Some attributes are missing in the player request. Among others `signatureTimestamp` and `embedUrl`, which are required for some videos. See https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/99226cb3d0b36eba04330b794578263ed8fdcba5/src/components/innertubeClient.js#L63

We should also continue to merge the attributes from the client context for the innertube player request.

Otherwise it looks very clean now!

**Comment by zerodytrash** [comment]
OK, I understand.

Here is a music video which does not work without `signatureTimestamp`: https://youtu.be/ycV6cnK3SIs
`embedUrl` is also required for some videos, but at the moment I can't find one.

**Comment by drunkwinter** [comment]
Almost thought I was on another website couple seconds in the music video :P

But yes, confirmed! Also found an old video you send me https://kworb.net/youtube/video/dmJefsOErr0.html where it only works with `embedUrl` included. Does the strategy (creator + auth) need `signatureTimestamp`?

On the side note, any chance we can delete discussion #65 and maybe communicate via Discord when needed? Promise won't spam you ;)

**Comment by zerodytrash** [comment]
> Does the strategy (creator + auth) need signatureTimestamp?

Yes, `WEB_CREATOR` also returns a `signatureCipher` based on the `signatureTimestamp`. I believe it is required for all clients to watch copyrighted content. This is now in place.

> On the side note, any chance we can delete discussion #65 and maybe communicate via Discord when needed? Promise won't spam you ;)

Oh, I forgot to answer that. Yes, we can communicate via Discord: ZerodyOne#4779 and we could set up a public Discord server where people can discuss and contribute their ideas.

**Pull request merged**
