### PR TITLE
[extension] implement settings page

### PR DESCRIPTION
**Pull request by drunkwinter**
Initial implementation of the settings page.

#### Linked issues:
- #136 
- #123

#### GIF:
Animation

### CODE REVIEW

**Comment by zerodytrash** [comment]
@drunkwinter can you test this?

**Comment by drunkwinter** [comment]
Yeah this will work because we are delaying the execution, my only concern with this approach was that we might encounter a race condition in the userscript somehow, someday.

**Comment by zerodytrash** [comment]
Yes, with this we delay the execution by a few milliseconds. But without any ugly workarounds (e.g. creating a copy of the settings in the localStorage) we will probably not find a better solution. Other extensions like Tampermonkey or Violentmonkey also need to retrieve settings for the activated userscripts. Maybe it is worth to have a look how this is done.

To find out how much `chrome.storage.sync` affects the execution, I measured the time.

content script
```javascript
    console.log("before settings", (new Date()).getTime());
    chrome.storage.sync.get('options', ({ options }) => {
        console.log("after settings", (new Date()).getTime());
```

userscript (config.js)
```javascript
if (IS_EXTENSION) {
    function applyConfig(options) {
        console.log("script loaded", (new Date()).getTime());
```

userscript (main.js)
```javascript
// Script configuration variables
export const UNLOCKABLE_PLAYABILITY_STATUSES = ['AGE_VERIFICATION_REQUIRED', 'AGE_CHECK_REQUIRED', 'LOGIN_REQUIRED'];
export const VALID_PLAYABILITY_STATUSES = ['OK', 'LIVE_STREAM_OFFLINE'];

console.log("script loaded", (new Date()).getTime());
```

Results:
```
before settings 1650075736980
after settings 1650075736982
script loaded 1650075736997
first unlock needed 1650075737079
```
Duration to retrieve the settings: **2ms**
Duration to inject and initialize the userscript: **15ms**
Time until the initial data goes through the interceptor: **82ms**

I have repeated the test several times. Sometimes the injection of the script takes up to 100ms (the time between `after settings` and `script loaded `). In such cases, sometimes the trick with the reload of the player is needed to unlock the video. What we can see from this is that creating the script tag to inject the script takes much more time than querying the settings. But surely this can also be different for other users and become noticeable differently there.

**Comment by Araxeus** [comment]
Cool design, wish my extension's menu looked as good 😄 

Youtube-Volume-Scroll

**Pull request merged**
