### PR TITLE
[extension] implement (in)active icon

### PR DESCRIPTION
**Pull request by drunkwinter**
Icon is inactive (gray) by default and switches to active (colored) when on YouTube.

**Tasks**
- [x] Switch to active on embed
- [x] Firefox support (MV2)

**Related issues**
- #123

### CODE REVIEW

**Comment by drunkwinter** [comment]
@zerodytrash Help is appreciated :)

**Comment by zerodytrash** [comment]
Love all these workarounds that are required to build a simple extension 😂👍

**Comment by zerodytrash** [comment]
@drunkwinter i believe this works.

**Comment by drunkwinter** [comment]
Nice, that's much better of an implementation! Merge whenever you want.

**Pull request merged**
