### PR TITLE
refactor(notification): replace with YouTube's native one

### PR DESCRIPTION
**Pull request by DrunkWinter**
The benefit of this change is that it requires less code and is more user friendly.

Needs testing and feedback if possible.

## Summary of changes
This PR contains the following changes:
- Replaced the old notification system in favor of YouTube's
- Changed some of the messages a bit

## Images
image
image

### CODE REVIEW

**Review by zerodytrash — COMMENTED** [review]
That's awesome! I didn't know that youtube has an externally accessible notification API. 

Works fine in Chrome and Firefox (WEB). But the mobile version of the YouTube website (MWEB) (m.youtube.com) uses a different notification system. The `tp-yt-paper-toast` element provided by desktop_polymer.js doesn't exist there. 

image

This is the element which is used on mobile. Do you know a way to interact with it? Otherwise we waive notifications on MWEB.

For the notification text, I would use the short version without "was".

> "Video was successfully unlocked!" => "Video successfully unlocked!"
> "Was unable to unlock this video 🙁 ..." => "Unable to unlock this video 🙁 ..."

(if this is grammatically correct, my english skills are not the best :')

**Comment by DrunkWinter** [comment]
Unfortunately mobile doesn't expose any obvious API, so this required more manual work.
Let me know what your think or if I should revert. I also changed the notification text to your liking.

**Comment by DrunkWinter** [comment]
Do you know how we could check if we are on desktop or mobile easily?

**Comment by DrunkWinter** [comment]
> Do you know how we could check if we are on desktop or mobile easily?

Ok. Currently I'm checking `window.Polymer`, seems the easiest way.

**Comment by zerodytrash** [comment]
> Ok. Currently I'm checking window.Polymer, seems the easiest way.

That should be okay.

Now it works on mobile as well. Good work!

**Pull request merged**
