### PR TITLE
[docs] add extension hyperlinks

### PR DESCRIPTION
**Pull request by drunkwinter**

### CODE REVIEW

**Comment by zerodytrash** [comment]
Chrome: Waiting for verification of my credit card to pay $5
Firefox: https://addons.mozilla.org/en-US/firefox/addon/youtube-age-restriction-bypass/
Opera: Waiting for approval
Edge: Waiting for approval

**Comment by bachig26** [comment]
will you be bringing the extension support to Safari and also in as iOS Safari extension? in later days maybe?

**Comment by zerodytrash** [comment]
@bachig26 Its already possible to use the userscript in Safari on macOS and iOS with the extension "Userscripts" https://apps.apple.com/us/app/userscripts/id1463298887

There are no plans to put this extension in the Apple App Store. But that can change...

**Comment by bachig26** [comment]
> @bachig26 Its already possible to use the userscript in Safari on macOS and iOS with the extension "Userscripts" https://apps.apple.com/us/app/userscripts/id1463298887
> 
> There are no plans to put this extension in the Apple App Store. But that can change...

it's good to hear about this, as I was unaware of this one. Thank you so much.

And also happy to see that 2022 started with a new milestone in the project by introducing the extension.
🎂🎉🎊🎆

**Comment by bachig26** [comment]
so the [README.md](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass#readme) will be updated after this PR is closed, right?

also, how long will it take to use in chrome [I'm using Vivaldi, that's why]?

**Comment by drunkwinter** [comment]
> so the [README.md](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass#readme) will be updated after this PR is closed, right?

Yes

> also, how long will it take to use in chrome [I'm using Vivaldi, that's why]?

No, ETA. @zerodytrash is doing what he can as fast as possible, but these have to go through a review process first which we don't have control over. And not to mention that it might not pass because of Google's policies or even if it passes it might get removed, so no certainty at this point.

**Comment by zerodytrash** [comment]
I am still waiting for google to send me a confirmation code by doing a small transaction on my credit card...
So far without success. So I don't know if that's going to happen...

image

For Opera, the review is still pending. According to the information found on the Opera forum, this process can take several months or even years. See https://forums.opera.com/topic/16609/very-long-extension-moderation-process/385

I think we need a lot of patience 😂

**Comment by zerodytrash** [comment]
> also, how long will it take to use in chrome [I'm using Vivaldi, that's why]?

You can simply use it with tampermonkey. That works just as well.

**Comment by bachig26** [comment]
> You can simply use it with tampermonkey. That works just as well.

At the moment, I’m using the violentmonkey. it’s just I want to try as an extension, that’s why I asked like how long will it take.

**Comment by bachig26** [comment]
> I am still waiting for google to send me a confirmation code by doing a small transaction on my credit card... So far without success. So I don't know if that's going to happen...
> 
> image
> 
> For Opera, the review is still pending. According to the information found on the Opera forum, this process can take several months or even years. See https://forums.opera.com/topic/16609/very-long-extension-moderation-process/385
> 
> I think we need a lot of patience 😂

If the extension is not approved, will there be an unsigned copy to load it as developer mode.

**Comment by zerodytrash** [comment]
> If the extension is not approved, will there be an unsigned copy to load it as developer mode.

Yes, have attached the packed extension to the last release. 
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/releases/tag/v2.3.5

extension_manifest_v3_chromium.zip should be the right version for vivaldi.

**Pull request merged**
