### PR TITLE
refactor: code quality improvements

### PR DESCRIPTION
**Pull request by DrunkWinter**
### Some of the changes include:
- Reorganized variable and function declarations
- Stripped variables of  `null` initialization
- Renamed some variable names
- Removed 2 unnecessary `try-catch` blocks
- Added a simple `document.createElement` wrapper
- Used `const` over `let` where possible
- Used optional chaining where possible
- Used arrow functions where plausible
- Used object destructing where plausible

Any feedback is appreciated.

### CODE REVIEW

**Comment by zerodytrash** [comment]
hi, thanks for your optimizations. Looks very clean now!
Let me know when you're done. Then I will test it.

**Comment by DrunkWinter** [comment]
> hi, thanks for your optimizations. Looks very clean now!
> Let me know when you're done. Then I will test it.

Thanks! I think it's done now, it just needs some extensive testing.

I was gonna do a refactor of the notifications, to use the native YouTube one, but I think that deserves it's own pull request. 
Not to mention that this pull request is getting to big ;)

**Comment by DrunkWinter** [comment]
Let me know if everything works accordingly on your end so I can cleanup the commits before merge.

**Review by zerodytrash — COMMENTED** [review]
Everything works! Tested in Chrome and Firefox.

- [x]  https://www.youtube.com/watch?v=7t0SqerlBA0 (innertube bypass used)
    - [x] With Login
    - [x] Without Login (sidebar + comments restored)
- [x]  https://www.youtube.com/watch?v=Cr381pDsSsA (account proxy used)
    - [x] With Login
    - [x] Without Login (sidebar + comments restored)

**Comment by DrunkWinter** [comment]
Okay cleaned up the commits. Good for merge!

**Comment by zerodytrash** [comment]
Then we are done :) thanks for your good work! Feel free to improve the notification too (it's still very messy at the moment).

I have intentionally not increased the version number of the script to avoid unnecessary update notices, since there are no functional differences.

**Pull request merged**
