### PR TITLE
[fix] description & related videos

### PR DESCRIPTION
**Pull request by drunkwinter**
This PR fixes the description and related videos.

### CODE REVIEW

**Comment by zerodytrash** [comment]
I have some problems to understand the fix. For me, the video suggestions work in the old version. What does this fix now?
And I think it would be nicer if the function `getNext` in the `innertubeClient` module is generic. This works better if you only pass the required information like the `videoId` and not the entire original response. And what about the `paylistId` and `playlistIndex`? That is missing now.

**Comment by drunkwinter** [comment]
For me it wasn't working for over a month now. 

If you noticed, the payload is the same as in PR #101. I did some testing and it seems that all the other parameters we include in the payload causes some kind of conflict, which causes it to stop working. So it was my idea that we better only provide the necessary parameters in the payload. The reason as to why i provide the original response to `getNext` is, so we can construct the payload from the initial response we have. Generic payloads won't work anymore as it can create conflicts with other methods, hence why i moved to constructing the entire payload separately for each strategy in #101. I did not include the `playlistId` and `playlistIndex` because I saw no effect with or without it, so I decided to omit it, trying to prevent a possible conflict now or in the future. Do you know of any use case for these parameters by any chance?

**Comment by zerodytrash** [comment]
> Do you know of any use case for these parameters by any chance?

No :) I read that YouTube provides different codecs and formats for different browsers. But I don't know if this is done via the client context which contains information like `browserName`, `browserVersion` and some other player related stuff. So far I could not find any errors without these parameters.

**Comment by zerodytrash** [comment]
I think we can merge it into main for now. before the next release we can test it more closely. Same for #101. You agree?

**Comment by drunkwinter** [comment]
Yeah that's fine, go ahead.

**Pull request merged**
